import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

public class PostRepositoryImpl implements IRepository<Post> {
    private List<Post> entities = new ArrayList<>();
    private java.sql.Connection con;
    public PostRepositoryImpl(){
        this.con = SocialNetworkService.getConnection();
    }

    /**
     * Se encarga de mapear um registro de la base de datos para converirlo en un objeto Post
     * @param rs
     * @return Un objeto Post
     * @throws SQLException
     */
    public Post bdToEntity(ResultSet rs) throws SQLException {
        return new Post(rs.getInt("id"),
                rs.getString("text"),
                rs.getInt("likes"),
                rs.getDate("date"),
                new UserRepositoryImpl().findById(rs.getInt("userId")));
    }

    /**
     * Consulta todos los registros de la tabla posts
     * @return Una lista de objetos Post
     * @throws SQLException
     */
    public List<Post> findAll() throws SQLException {

        List<Post> posts = new ArrayList<>();

        Statement st = this.con.createStatement();
        //Ejecutar la consulta, guardando los datos devueltos en un Resulset
        ResultSet rs = st.executeQuery("SELECT * FROM posts ORDER BY date DESC");

        while(rs.next()){
            //Mapeamos el registro de la BD en un User
            Post post =  bdToEntity(rs);
            //Añadir el User al conjunto de users
            posts.add(post);
        }
        return posts;
    }

    /**
     * Busca un post por id en la tabla posts
     * @param id
     * @return El objeto Post o null si no existe
     * @throws SQLException
     */
    public Post findById(int id) throws SQLException {
        PreparedStatement st = con.prepareStatement("SELECT * FROM posts WHERE id = ? ");
        st.setInt(1, id);

        ResultSet rs = st.executeQuery();
        Post p = null;
        //Si la consulta devuelve algún resultado ...
        if (rs.next()){
            // ... lo mapeamos a un objeto Usuario
            p = bdToEntity(rs);
        }
        //Devolvemos el Post ya mapeado
        return p;
    }
    /**
     * Guarda el post Post en la base de datos, insertando si id es distinto de -1 o actualizando aquél
     * Sólo se pueden crear post no actualizar
     * registro con dicho id
     * @param post
     * @throws SQLException
     */
    public void save(Post post) throws SQLException{
        if (post.getId() == -1){
            ResultSet rs;
            PreparedStatement st = null;
            String query = "INSERT INTO posts (text, likes, date, userId) VALUES (?, ?, ?, ?)";
            //Fijáos en Statement.RETURN_GENERATED_KEYS. Permite recuperar el campo ID autogenerado por MySql
            st = con.prepareStatement(query, Statement.RETURN_GENERATED_KEYS);

            st.setString(1, post.getText());
            st.setInt(2, post.getLikes());
            st.setDate(3, post.getDate());
            st.setInt(4, post.getUser().getId());

            st.executeUpdate();

            //Recuperar el id autogenerado
            rs = st.getGeneratedKeys();
            //Este ResultSet solo puede contener un registro: el ID autogenerado

            if (rs.next()){
                //Ahora ya sabemos cuál es el nuevo id del Usuario
                post.setId(rs.getInt(1));
                System.out.println("Autogenerated ID:  " + post.getId());
            }
        }
    }

    /**
     * Elimina de la base de datos el Post post
     * @param post
     * @throws SQLException
     */
    public void delete(Post post) throws SQLException {
        PreparedStatement st = con.prepareStatement("DELETE FROM posts WHERE id = ?");
        st.setInt(1, post.getId());
        st.executeUpdate();
        st.close();
    }
}
