import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

public class UserRepositoryImpl implements IRepository<User> {
    private List<User> entities = new ArrayList<>();
    private java.sql.Connection con;
    public UserRepositoryImpl(){
        this.con = SocialNetworkService.getConnection();
    }

    /**
     * Se encarga de mapear um registro de la base de datos para converirlo en un objeto User
     * @param rs
     * @return Un objeto User
     * @throws SQLException
     */
    public User bdToEntity(ResultSet rs) throws SQLException {
        return new User(rs.getInt("id"), rs.getString("name"), rs.getString("lastName"));
    }

    /**
     * Consulta todos los registros de la tabla users
     * @return Una lista de objetos User
     * @throws SQLException
     */
    public List<User> findAll() throws SQLException {

        List<User> users = new ArrayList<>();

        Statement st = this.con.createStatement();
        //Ejecutar la consulta, guardando los datos devueltos en un Resulset
        ResultSet rs = st.executeQuery("SELECT * FROM users ORDER BY lastName, name");

        while(rs.next()){
            //Mapeamos el registro de la BD en un User
            User u =  bdToEntity(rs);
            //Añadir el User al conjunto de users
            users.add(u);
        }
        return users;
    }

    /**
     * Busca un usuario por id en la tabla users
     * @param id
     * @return El objeto User o null si no existe
     * @throws SQLException
     */
public User findById(int id) throws SQLException {
        PreparedStatement st = con.prepareStatement("SELECT * FROM users WHERE id = ? ");
        st.setInt(1, id);

        ResultSet rs = st.executeQuery();
        User u = null;
        //Si la consulta devuelve algún resultado ...
        if (rs.next()){
            // ... lo mapeamos a un objeto Usuario
            u = bdToEntity(rs);
        }
        //Devolvemos el Usuario ya mapeado
        return u;
    }

    public List<User> findByName(String name) throws SQLException {

        List<User> users = new ArrayList<>();

        PreparedStatement st = this.con.prepareStatement("SELECT * FROM users WHERE name LIKE ?");
        st.setString(1, "%" + name + "%");
        //Ejecutar la consulta, guardando los datos devueltos en un Resulset
        ResultSet rs = st.executeQuery();

        while(rs.next()){
            //Mapeamos el registro de la BD en un Usuario
            User u =  bdToEntity(rs);
            //Añadir el Usuario al conjunto de users
            users.add(u);
        }
        return users;
    }

    /**
     * Guarda el usuario User en la base de datos, insertando si id es distinto de -1 o actualizando aquél
     * registro con dicho id
     * @param user
     * @throws SQLException
     */
    public void save(User user) throws SQLException{
        if (user.getId() == -1){
            ResultSet rs;
            PreparedStatement st = null;
            String query = "INSERT INTO users (name, lastName) VALUES (?, ?)";
            //Fijáos en Statement.RETURN_GENERATED_KEYS. Permite recuperar el campo ID autogenerado por MySql
            st = con.prepareStatement(query, Statement.RETURN_GENERATED_KEYS);

            st.setString(1, user.getName());
            st.setString(2, user.getLastName());

            st.executeUpdate();

            //Recuperar el id autogenerado
            rs = st.getGeneratedKeys();
            //Este ResultSet solo puede contener un registro: el ID autogenerado

            if (rs.next()){
                //Ahora ya sabemos cuál es el nuevo id del Usuario
                user.setId(rs.getInt(1));
                System.out.println("Autogenerated ID:  " + user.getId());
            }
        }else{
            PreparedStatement st = con.prepareStatement("UPDATE users SET name = ?, lastName = ? WHERE id = ?");
            st.setString(1, user.getName());
            st.setString(2, user.getLastName());
            st.setInt(3, user.getId());

            st.executeUpdate();
        }

    }

    /**
     * Elimina de la base de datos el usuario user
     * @param user
     * @throws SQLException
     */
    public void delete(User user) throws SQLException {
        PreparedStatement st = con.prepareStatement("DELETE FROM users WHERE id = ?");
        st.setInt(1, user.getId());
        st.executeUpdate();
        st.close();
    }
}
